-- DB Schema file

CREATE TABLE  IF NOT EXISTS POST(
    ID BIGINT PRIMARY KEY,
    CONTENT VARCHAR(255),
    LASTUPDATEDDATE TIMESTAMP,
    TITLE VARCHAR(255),
    BLOGGERID BIGINT
);

CREATE TABLE  IF NOT EXISTS BLOGGER(
    ID BIGINT PRIMARY KEY auto_increment,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    LASTUPDATEDDATE TIMESTAMP,
    EMAIL VARCHAR(255),
    LOGIN VARCHAR(255),
    PASSWORD VARCHAR(255)
);