-- DB Schema file
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS BLOGGER;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS authorities;

CREATE TABLE IF NOT EXISTS GROUPS (
  	ID BIGINT PRIMARY KEY auto_increment,
  	name varchar_ignorecase(50) not null
);

CREATE TABLE IF NOT EXISTS BLOGGER(
    ID BIGINT PRIMARY KEY auto_increment,
    --ID BIGINT generated by default as identity(start with 0) primary key,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    LASTUPDATED TIMESTAMP,
    EMAIL VARCHAR(255),
    isSubscribedByEmail BOOLEAN,
    LOGIN VARCHAR(255),
    PASSWORD VARCHAR(255),
    GROUP_ID bigint,
    constraint fk_blogger_group foreign key(GROUP_ID) references GROUPS(id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

CREATE TABLE  IF NOT EXISTS POST(
    ID BIGINT PRIMARY KEY auto_increment,
    CONTENT BLOB,
    LASTUPDATEDDATE TIMESTAMP,
    TITLE VARCHAR(255),
    BLOGGER_ID BIGINT,
    constraint fk_post_blogger foreign key(BLOGGER_ID) references BLOGGER(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS authorities (
  	ID BIGINT PRIMARY KEY auto_increment,
	group_id bigint not null,
  	name varchar(50) not null,
  	constraint fk_authorities_group foreign key(group_id) references groups(id)
);
